### PR TITLE
8 uhul

### PR DESCRIPTION
**Pull request by jachym**
* Add support for WMTS layers
* Add some first set of UHUL layers

### CODE REVIEW

**Comment by ruz76** [comment]
@jachym The WMTS does not work for me. QGIS 3.16.
WMTS:http://apollo.uhul.cz/erdas-iws/ogc/wmts/DPZE?service=wmts&request=getcapabilities,layer=LEDR_2019,tilematrixset=GoogleMapsCompatibleExt:epsg:3857,format=image/png
2021-03-15T21:03:02     CRITICAL    Error : The layer was not valid and could not be loaded.

**Comment by jachym** [comment]
Hmm, will have to ask @wonder-sk how to deal with WMTS layers properly

**Comment by wonder-sk** [comment]
Use "wms" provider for WMTS layers - it has better integration that wmts from gdal (e.g. you can watch as tiles are getting loaded).

How to find out URI in QGIS:
1. add wms/wmts connection to http://apollo.uhul.cz/erdas-iws/ogc/wmts/DPZE?service=wmts&request=getcapabilities
2. load the desired layer from that connection
3. open layer properties > Information tab. Copy what you see in "Source"

For this particular data source I got this:

`contextualWMSLegend=0&crs=EPSG:3857&dpiMode=7&featureCount=10&format=image/png&layers=LEDR_2019&styles=default&tileMatrixSet=GoogleMapsCompatibleExt:epsg:3857&url=http://apollo.uhul.cz/erdas-iws/ogc/wmts/DPZE?service%3Dwmts%26request%3Dgetcapabilities`

(some bits may not be necessary and could be removed - e.g. `contextualWMSLegend` or `featureCount`)

**Comment by jachym** [comment]
I did exactly this, did bot work at the first attempt

will try again

thank you

**Comment by jachym** [comment]
@ruz76  can you try please?

Uhul: mapa dřevin 2019

**Comment by ruz76** [comment]
Perfect @jachym Works like a charm.

**Pull request merged**
