### PR TITLE
improve ui layout 

### PR DESCRIPTION
**Pull request by jakubsimek97**
layout changed to grid 
minimum widget size defined

### CODE REVIEW

**Review by landam — APPROVED** [review]

**Review by ruz76 — COMMENTED** [review]
No sure what this request is for. What is wrong on the current GUI?

**Comment by landam** [comment]
> No sure what this request is for. What is wrong on the current GUI?

Widgets are organized into grid layout. Minimum size of widgets are now also defined. Try to change windows size...

**Comment by landam** [comment]
Original version: 

(widgets overlaps)

Screenshot from 2021-04-09 14-05-54

(no minimum size defined)

Screenshot from 2021-04-09 14-06-00

**Comment by landam** [comment]
New version:

Screenshot from 2021-04-09 14-07-37

**Comment by landam** [comment]
@ruz76 Students started with something extra easy just to understand how PR works.

**Pull request merged**
